baseurl = "your-site-address"
title = "Winning"
theme = "hugo-theme-Winning"
themesdir = "../.."

disableKinds = ["RSS"]
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en-us"
[taxonomies]

[author]
    name = "your-name"
    email = "your-email"