theme = "winning"
title = "Winning"

baseurl = "your-site-address"
title = "your-site-name"
themesdir = "../.."

disableKinds = ["RSS"]
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en-us"
[taxonomies]